config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens

  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: 'Kitten was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to kitten_path, notice: 'Kitten was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    kitten = Kitten.find(params[:id])
    kitten.destroy

    redirect_to root_path, notice: "Kitten deleted, how could you do that ;("
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div>
  <%= form_with(model: @kitten) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :age %>
      <%= form.text_field :age %>
    </div>
    <div>
      <%= form.label :cuteness %>
      <%= form.text_field :cuteness %>
    </div>
    <div>
      <%= form.label :softness %>
      <%= form.text_field :softness %>
    </div>
    <div class="actions">
      <%= form.submit 'Submit' %>
    </div>
  <% end %>
</div>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/index.html.erb
<div>
  <% @kittens.each do |kitten| %>
    <%= link_to kitten.name, kitten_path(kitten) %>
  <% end %>
</div>

<div>
  <%= link_to 'New Kitten', new_kitten_path %>
</div>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<div>
  <%= render 'form', kitten: @kitten.id %>
</div>

app/views/kittens/show.html.erb
<div>
  <%= @kitten.name %>
<div>
<div>
  <%= link_to 'Edit', edit_kitten_path(@kitten) %>
  <%= link_to 'Delete', kitten_path(@kitten), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>